import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import { LanguageProvider } from '@/context/LanguageContext';
import { AuthProvider } from '@/context/AuthContext';
import Footer from '@/components/Footer';
import { ResponseProvider } from '@/context/ResponseContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LanguageProvider>
          <AuthProvider>
            <ResponseProvider>
              <>
                <Header />
                {children}
                <Footer />
              </>
            </ResponseProvider>
          </AuthProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
